apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark
spec:
  template:
    metadata:
      name: benchmark
    spec:
      containers:
      - name: benchmark
        image: benchmark:v0.1
        command: ["/bin/bash", "-c", ""]
        volumeMounts:
        - mountPath: "/mnt/pv"
          name: local-storage-volume
      volumes:
      - name: local-storage-volume
        persistentVolumeClaim:
          claimName: local-storage-claim
      restartPolicy: Never
