apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark
spec:
  template:
    metadata:
      name: benchmark
    spec:
      containers:
      - name: benchmark
        image: openstack-docker-registry:5000/benchmark:0.1
        command: ["/bin/bash", "-c", "/home/centos/run_benchmark.sh"]
        volumeMounts:
        - mountPath: "/mnt/pv"
          name: local-storage-volume
      volumes:
      - name: local-storage-volume
        persistentVolumeClaim:
          claimName: local-storage-claim
      restartPolicy: Never
