apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  annotations:
    "volume.alpha.kubernetes.io/node-affinity": '{
      "requiredDuringSchedulingIgnoredDuringExecution": {
        "nodeSelectorTerms": [
          { "matchExpressions": [
            { "key": "kubernetes.io/hostname",
              "operator": "In",
              "values": ["openstack-erikube-node1-dapeng.onecloud.poc"]
            }
          ]}
         ]}
        }'
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disks/vol

# "openstack-erikube-node1-dapeng.onecloud.poc" with the name of kubernetes node that is hosting this local storage disk
# "5Gi" with the required size of storage volume, same as specified in PVC
# "local-storage" with the name of storage class to associate with this local volume
# "/mnt/disks/vol" with the path to the mount point of local volumes