apiVersion: batch/v1
kind: Job
metadata:
  name: disk-benchmark
spec:
  template:
    metadata:
      name: disk-benchmark
    spec:
      containers:
      - name: disk-benchmark
        image: docker.io/dapeng1011/disk-benchmarker:0.1
        resources:
          requests:
            memory: 3Gi
        command: ["/bin/bash", "-c", "/home/run_benchmark.sh"]
        volumeMounts:
        - mountPath: "/mnt/pv"
          name: local-storage-volume
      volumes:
      - name: local-storage-volume
        persistentVolumeClaim:
          claimName: local-storage-claim
      restartPolicy: Never
