apiVersion: batch/v1
kind: Job
metadata:
  name: alpine-write
spec:
  template:
    metadata:
      name: alpine-write
    spec:
      containers:
      - name: alpine-write
        image: alpine
        command: ["sh","-c"]
        args:
          - dd if=/dev/zero of=/mnt/pv/test.img bs=1G count=1 oflag=dsync
        volumeMounts:
        - mountPath: "/mnt/pv"
          name: test-volume
      volumes:
      - name: test-volume
        persistentVolumeClaim:
          claimName: test-claim
      restartPolicy: Never
